# Generated by Django 5.2 on 2025-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('word_state', models.CharField(max_length=20)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('InProgress', 'In Progress'), ('Won', 'Won'), ('Lost', 'Lost')], default='InProgress', max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
