# Generated by Django 5.2 on 2025-07-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Won', 'Won'), ('Lost', 'Lost')], default='InProgress', max_length=11),
        ),
        migrations.AlterField(
            model_name='game',
            name='word',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='game',
            name='word_state',
            field=models.CharField(max_length=11),
        ),
    ]
